/* =============================================================
   COLEÇÃO DE DESENHOS: todos os desenhos que vieram com o app.

   É daqui que sai a tela "Trocar desenho", aberta pelo cartão do
   exercício. Ela mostra só os desenhos PARECIDOS com o exercício: os
   do mesmo grupo (ver GRUPOS_DE_DESENHO, no fim do arquivo). Escolher
   um desenho só muda o que aparece no cartão: o histórico do
   exercício não é tocado.

   Os arquivos moram em imagens/colecao, reduzidos para 800px em tons
   de cinza, a partir dos originais da pasta Ilustracoes_Treino.
   O número na frente é o mesmo do arquivo original. Para acrescentar
   um desenho, é só pôr o arquivo na pasta e uma linha aqui: o sw.js
   lê esta lista sozinho, e o grupo sai do nome.
   ============================================================= */

const COLECAO_DE_DESENHOS = [
  { arquivo: "imagens/colecao/001-agachamento-smith.webp", nome: "Agachamento no Smith" },
  { arquivo: "imagens/colecao/002-agachamento-goblet.webp", nome: "Agachamento goblet" },
  { arquivo: "imagens/colecao/003-supino-sentado-maquina.webp", nome: "Supino sentado na máquina" },
  { arquivo: "imagens/colecao/004-puxada-alta.webp", nome: "Puxada alta" },
  { arquivo: "imagens/colecao/005-flexora-sentada.webp", nome: "Flexora sentada" },
  { arquivo: "imagens/colecao/006-elevacao-lateral-halteres.webp", nome: "Elevação lateral com halteres" },
  { arquivo: "imagens/colecao/007-rosca-scott.webp", nome: "Rosca Scott" },
  { arquivo: "imagens/colecao/008-elevacao-panturrilhas.webp", nome: "Elevação de panturrilhas" },
  { arquivo: "imagens/colecao/009-terra-romeno-halteres.webp", nome: "Levantamento romeno com halteres" },
  { arquivo: "imagens/colecao/010-supino-inclinado-barra-anilhas.webp", nome: "Supino inclinado com barra e anilhas" },
  { arquivo: "imagens/colecao/011-remada-sentada-polia-pegada-fechada.webp", nome: "Remada sentada na polia, pegada fechada" },
  { arquivo: "imagens/colecao/012-cadeira-extensora.webp", nome: "Cadeira extensora" },
  { arquivo: "imagens/colecao/013-desenvolvimento-ombros-halteres.webp", nome: "Desenvolvimento de ombros com halteres" },
  { arquivo: "imagens/colecao/014-triceps-polia-corda.webp", nome: "Tríceps na polia com corda" },
  { arquivo: "imagens/colecao/015-prancha.webp", nome: "Prancha" },
  { arquivo: "imagens/colecao/016-voador-pec-deck.webp", nome: "Voador ou pec deck" },
  { arquivo: "imagens/colecao/017-remada-polia-baixa.webp", nome: "Remada na polia baixa" },
  { arquivo: "imagens/colecao/018-rosca-halteres.webp", nome: "Rosca com halteres em pé" },
  { arquivo: "imagens/colecao/019-leg-press-45.webp", nome: "Leg press 45 graus" },
  { arquivo: "imagens/colecao/020-abdominal-curto-deitado.webp", nome: "Abdominal curto deitado (crunch)" },
  { arquivo: "imagens/colecao/021-rosca-halteres-sentado.webp", nome: "Rosca com halteres sentado" },
  { arquivo: "imagens/colecao/022-cadeira-adutora.webp", nome: "Cadeira adutora" },
  { arquivo: "imagens/colecao/023-cadeira-abdutora.webp", nome: "Cadeira abdutora" },
  { arquivo: "imagens/colecao/024-flexora-deitada.webp", nome: "Flexora deitada" },
  { arquivo: "imagens/colecao/025-panturrilha-sentado.webp", nome: "Panturrilha sentada" },
  { arquivo: "imagens/colecao/026-voador-inverso.webp", nome: "Voador inverso na máquina" },
  { arquivo: "imagens/colecao/027-elevacao-lateral-polia.webp", nome: "Elevação lateral unilateral na polia" },
  { arquivo: "imagens/colecao/028-rosca-polia-barra.webp", nome: "Rosca de bíceps na polia" },
  { arquivo: "imagens/colecao/029-rosca-martelo-polia.webp", nome: "Rosca martelo na polia com corda" },
  { arquivo: "imagens/colecao/030-triceps-polia-barra.webp", nome: "Tríceps na polia com barra" },
  { arquivo: "imagens/colecao/031-triceps-acima-cabeca-polia.webp", nome: "Tríceps acima da cabeça na polia" },
  { arquivo: "imagens/colecao/032-face-pull-polia.webp", nome: "Face pull com corda" },
  { arquivo: "imagens/colecao/033-puxada-bracos-estendidos.webp", nome: "Puxada na polia com braços estendidos" },
  { arquivo: "imagens/colecao/034-crucifixo-crossover.webp", nome: "Crucifixo no crossover" },
  { arquivo: "imagens/colecao/035-remada-unilateral-polia-sentado.webp", nome: "Remada unilateral na polia sentado" },
  { arquivo: "imagens/colecao/036-supino-inclinado-maquina.webp", nome: "Supino inclinado na máquina" },
  { arquivo: "imagens/colecao/037-leg-press-horizontal.webp", nome: "Leg press horizontal sentado" },
  { arquivo: "imagens/colecao/038-elevacao-frontal-polia.webp", nome: "Elevação frontal na polia" },
  { arquivo: "imagens/colecao/039-extensao-quadril-polia.webp", nome: "Extensão de quadril na polia" },
  { arquivo: "imagens/colecao/040-abducao-quadril-polia.webp", nome: "Abdução de quadril na polia" },
  { arquivo: "imagens/colecao/041-aducao-quadril-polia.webp", nome: "Adução de quadril na polia" },
  { arquivo: "imagens/colecao/042-crucifixo-inclinado-polia.webp", nome: "Crucifixo de baixo para cima no crossover" },
  { arquivo: "imagens/colecao/043-elevacao-pelvica-banco-halter.webp", nome: "Elevação pélvica no banco com halter" },
  { arquivo: "imagens/colecao/044-ponte-gluteos-chao.webp", nome: "Ponte de glúteos no chão" },
  { arquivo: "imagens/colecao/045-dead-bug.webp", nome: "Dead bug (inseto morto)" },
  { arquivo: "imagens/colecao/046-panturrilha-leg-press.webp", nome: "Panturrilha no leg press" },
  { arquivo: "imagens/colecao/047-hack-squat.webp", nome: "Hack squat" },
  { arquivo: "imagens/colecao/048-sissy-squat.webp", nome: "Sissy squat no aparelho" },
  { arquivo: "imagens/colecao/049-gluteo-maquina.webp", nome: "Extensão de quadril na máquina" },
  { arquivo: "imagens/colecao/050-hip-thrust-maquina.webp", nome: "Elevação pélvica na máquina" },
  { arquivo: "imagens/colecao/051-extensao-quadril-banco.webp", nome: "Extensão de quadril no banco a 45 graus" },
  { arquivo: "imagens/colecao/052-paralelas-livre-ereto.webp", nome: "Paralelas livres com tronco ereto" },
  { arquivo: "imagens/colecao/053-barra-fixa-pronada-media.webp", nome: "Barra fixa com pegada pronada média" },
  { arquivo: "imagens/colecao/054-desenvolvimento-maquina.webp", nome: "Desenvolvimento de ombros na máquina" },
  { arquivo: "imagens/colecao/055-paralelas-graviton-ereto.webp", nome: "Paralelas no graviton com tronco ereto" },
  { arquivo: "imagens/colecao/056-barra-fixa-graviton-media.webp", nome: "Barra fixa no graviton com pegada média" },
  { arquivo: "imagens/colecao/057-agachamento-power-rack.webp", nome: "Agachamento com barra no power rack" },
  { arquivo: "imagens/colecao/058-supino-reto-barra-rack.webp", nome: "Supino reto com barra no power rack" },
  { arquivo: "imagens/colecao/059-rack-pull.webp", nome: "Rack pull" },
  { arquivo: "imagens/colecao/060-abdominal-articulado.webp", nome: "Abdominal articulado na máquina" },
  { arquivo: "imagens/colecao/061-pull-through.webp", nome: "Pull-through na polia" },
  { arquivo: "imagens/colecao/062-esteira-caminhada.webp", nome: "Caminhada na esteira" },
  { arquivo: "imagens/colecao/063-esteira-corrida.webp", nome: "Corrida na esteira" },
  { arquivo: "imagens/colecao/064-bicicleta-ergometrica.webp", nome: "Bicicleta ergométrica" },
  { arquivo: "imagens/colecao/065-leg-press-pes-altos.webp", nome: "Leg press, pés altos" },
  { arquivo: "imagens/colecao/066-leg-press-pes-baixos.webp", nome: "Leg press, pés baixos" },
  { arquivo: "imagens/colecao/067-leg-press-base-aberta.webp", nome: "Leg press, base aberta" },
  { arquivo: "imagens/colecao/068-leg-press-base-fechada.webp", nome: "Leg press, base fechada" },
  { arquivo: "imagens/colecao/069-leg-press-unilateral.webp", nome: "Leg press, unilateral" },
  { arquivo: "imagens/colecao/070-hack-base-aberta.webp", nome: "Hack squat, base aberta" },
  { arquivo: "imagens/colecao/071-hack-pes-altos.webp", nome: "Hack squat, pés altos" },
  { arquivo: "imagens/colecao/072-hack-pes-baixos.webp", nome: "Hack squat, pés baixos" },
  { arquivo: "imagens/colecao/073-hack-parcial.webp", nome: "Hack squat, amplitude parcial" },
  { arquivo: "imagens/colecao/074-smith-agachamento-pes-frente.webp", nome: "Agachamento no Smith com pés à frente" },
  { arquivo: "imagens/colecao/075-smith-avanco.webp", nome: "Avanço no Smith" },
  { arquivo: "imagens/colecao/076-smith-bulgaro.webp", nome: "Agachamento búlgaro no Smith" },
  { arquivo: "imagens/colecao/077-smith-romeno.webp", nome: "Levantamento romeno no Smith" },
  { arquivo: "imagens/colecao/078-smith-hip-thrust.webp", nome: "Elevação pélvica no Smith" },
  { arquivo: "imagens/colecao/079-smith-panturrilha.webp", nome: "Panturrilha no Smith" },
  { arquivo: "imagens/colecao/080-smith-supino.webp", nome: "Supino reto no Smith" },
  { arquivo: "imagens/colecao/081-smith-desenvolvimento.webp", nome: "Desenvolvimento de ombros no Smith" },
  { arquivo: "imagens/colecao/082-sissy-carga.webp", nome: "Sissy squat com carga junto ao peito" },
  { arquivo: "imagens/colecao/083-sissy-apoio-maos.webp", nome: "Sissy squat com apoio das mãos" },
  { arquivo: "imagens/colecao/084-sissy-parcial.webp", nome: "Sissy squat com amplitude parcial" },
  { arquivo: "imagens/colecao/085-extensora-unilateral.webp", nome: "Cadeira extensora unilateral" },
  { arquivo: "imagens/colecao/086-flexora-sentada-unilateral.webp", nome: "Flexora sentada unilateral" },
  { arquivo: "imagens/colecao/087-flexora-deitada-unilateral.webp", nome: "Flexora deitada unilateral" },
  { arquivo: "imagens/colecao/088-abdutora-inclinada.webp", nome: "Cadeira abdutora com tronco inclinado" },
  { arquivo: "imagens/colecao/089-gluteo-maquina-tronco-ereto.webp", nome: "Extensão de quadril na máquina com tronco mais ereto" },
  { arquivo: "imagens/colecao/090-hip-thrust-maquina-unilateral.webp", nome: "Elevação pélvica unilateral na máquina" },
  { arquivo: "imagens/colecao/091-extensao-banco-carga.webp", nome: "Extensão no banco a 45 graus com carga" },
  { arquivo: "imagens/colecao/092-extensao-banco-tronco.webp", nome: "Extensão do tronco no banco a 45 graus" },
  { arquivo: "imagens/colecao/093-panturrilha-sentada-unilateral.webp", nome: "Panturrilha sentada unilateral" },
  { arquivo: "imagens/colecao/094-supino-maquina-neutro.webp", nome: "Supino sentado na máquina, pegada neutra" },
  { arquivo: "imagens/colecao/095-supino-maquina-unilateral.webp", nome: "Supino sentado na máquina unilateral" },
  { arquivo: "imagens/colecao/096-supino-inclinado-halteres.webp", nome: "Supino inclinado com halteres" },
  { arquivo: "imagens/colecao/097-supino-inclinado-halteres-neutro.webp", nome: "Supino inclinado com halteres, pegada neutra" },
  { arquivo: "imagens/colecao/098-supino-inclinado-maquina-unilateral.webp", nome: "Supino inclinado na máquina unilateral" },
  { arquivo: "imagens/colecao/099-supino-inclinado-maquina-neutro.webp", nome: "Supino inclinado na máquina, pegada neutra" },
  { arquivo: "imagens/colecao/100-pec-deck-unilateral.webp", nome: "Peck deck unilateral" },
  { arquivo: "imagens/colecao/101-pec-deck-reverso-unilateral.webp", nome: "Peck deck reverso unilateral" },
  { arquivo: "imagens/colecao/102-pec-deck-reverso-neutro.webp", nome: "Peck deck reverso, pegada neutra" },
  { arquivo: "imagens/colecao/103-desenvolvimento-maquina-neutro.webp", nome: "Desenvolvimento na máquina, pegada neutra" },
  { arquivo: "imagens/colecao/104-desenvolvimento-barra-sentado.webp", nome: "Desenvolvimento com barra sentado" },
  { arquivo: "imagens/colecao/105-desenvolvimento-barra-em-pe.webp", nome: "Desenvolvimento com barra em pé" },
  { arquivo: "imagens/colecao/106-desenvolvimento-halteres-em-pe.webp", nome: "Desenvolvimento com halteres em pé" },
  { arquivo: "imagens/colecao/107-desenvolvimento-halteres-neutro.webp", nome: "Desenvolvimento com halteres, pegada neutra" },
  { arquivo: "imagens/colecao/108-scott-barra-reta.webp", nome: "Rosca Scott com barra reta" },
  { arquivo: "imagens/colecao/109-scott-halter-unilateral.webp", nome: "Rosca Scott unilateral com halter" },
  { arquivo: "imagens/colecao/110-scott-halteres-bilateral.webp", nome: "Rosca Scott bilateral com halteres" },
  { arquivo: "imagens/colecao/111-scott-pegada-aberta.webp", nome: "Rosca Scott com barra W, pegada aberta" },
  { arquivo: "imagens/colecao/112-scott-pegada-fechada.webp", nome: "Rosca Scott com barra W, pegada fechada" },
  { arquivo: "imagens/colecao/113-paralelas-livre-inclinado.webp", nome: "Paralelas livres com tronco inclinado" },
  { arquivo: "imagens/colecao/114-paralelas-graviton-inclinado.webp", nome: "Paralelas no graviton com tronco inclinado" },
  { arquivo: "imagens/colecao/115-crucifixo-crossover-medio.webp", nome: "Crucifixo no crossover, polias médias" },
  { arquivo: "imagens/colecao/116-puxada-fechada.webp", nome: "Puxada alta, fechada" },
  { arquivo: "imagens/colecao/117-puxada-neutra.webp", nome: "Puxada alta, neutra" },
  { arquivo: "imagens/colecao/118-puxada-supinada.webp", nome: "Puxada alta, supinada" },
  { arquivo: "imagens/colecao/119-puxada-unilateral.webp", nome: "Puxada alta, unilateral" },
  { arquivo: "imagens/colecao/120-remada-aberta.webp", nome: "Remada sentada na polia, pegada aberta" },
  { arquivo: "imagens/colecao/121-barra-fixa-aberta.webp", nome: "Barra fixa, pronada aberta" },
  { arquivo: "imagens/colecao/122-barra-fixa-fechada.webp", nome: "Barra fixa, pronada fechada" },
  { arquivo: "imagens/colecao/123-barra-fixa-neutra.webp", nome: "Barra fixa, neutra" },
  { arquivo: "imagens/colecao/124-barra-fixa-supinada.webp", nome: "Barra fixa, supinada" },
  { arquivo: "imagens/colecao/125-barra-fixa-elastico.webp", nome: "Barra fixa, com elástico" },
  { arquivo: "imagens/colecao/126-graviton-aberta.webp", nome: "Barra fixa no graviton, pronada aberta" },
  { arquivo: "imagens/colecao/127-graviton-fechada.webp", nome: "Barra fixa no graviton, pronada fechada" },
  { arquivo: "imagens/colecao/128-graviton-neutra.webp", nome: "Barra fixa no graviton, neutra" },
  { arquivo: "imagens/colecao/129-graviton-supinada.webp", nome: "Barra fixa no graviton, supinada" },
  { arquivo: "imagens/colecao/130-desenvolvimento-power-rack.webp", nome: "Desenvolvimento com barra no power rack" },
  { arquivo: "imagens/colecao/131-barra-fixa-power-rack.webp", nome: "Barra fixa no power rack" },
  { arquivo: "imagens/colecao/132-prancha-lateral.webp", nome: "Prancha lateral" },
  { arquivo: "imagens/colecao/133-prancha-joelhos.webp", nome: "Prancha com apoio nos joelhos" },
  { arquivo: "imagens/colecao/134-prancha-alta.webp", nome: "Prancha alta nas mãos" },
  { arquivo: "imagens/colecao/135-prancha-toque-ombros.webp", nome: "Prancha com toque nos ombros" },
  { arquivo: "imagens/colecao/136-abdominal-articulado-curto.webp", nome: "Abdominal articulado, amplitude curta" },
  { arquivo: "imagens/colecao/137-abdominal-articulado-completo.webp", nome: "Abdominal articulado, maior amplitude" },
  { arquivo: "imagens/colecao/138-supino-reto-halteres.webp", nome: "Supino reto com halteres" },
  { arquivo: "imagens/colecao/139-remada-unilateral-halter.webp", nome: "Remada unilateral com halter" },
  { arquivo: "imagens/colecao/140-triceps-halter-acima-cabeca.webp", nome: "Tríceps acima da cabeça com halter" },
  { arquivo: "imagens/colecao/141-avanco-halteres.webp", nome: "Avanço com halteres" },
  { arquivo: "imagens/colecao/142-bulgaro-halteres.webp", nome: "Agachamento búlgaro com halteres" },
  { arquivo: "imagens/colecao/143-panturrilha-halteres.webp", nome: "Panturrilha com halteres" },
  { arquivo: "imagens/colecao/144-remada-curvada-barra.webp", nome: "Remada curvada com barra" },
  { arquivo: "imagens/colecao/145-rosca-barra.webp", nome: "Rosca direta com barra" },
  { arquivo: "imagens/colecao/146-romeno-barra.webp", nome: "Levantamento romeno com barra" },
  { arquivo: "imagens/colecao/147-hip-thrust-barra.webp", nome: "Elevação pélvica com barra" },
  { arquivo: "imagens/colecao/148-esteira-inclinada.webp", nome: "Caminhada na esteira inclinada" },
  { arquivo: "imagens/colecao/149-elevacao-frontal-halteres.webp", nome: "Elevação frontal com halteres" },
  { arquivo: "imagens/colecao/150-rosca-martelo-sentado-halteres.webp", nome: "Rosca martelo sentado com halteres" },
  { arquivo: "imagens/colecao/151-triceps-testa-barra-w.webp", nome: "Tríceps testa com barra W" },
  { arquivo: "imagens/colecao/152-rosca-concentrada-halter.webp", nome: "Rosca concentrada com halter" },
  { arquivo: "imagens/colecao/153-rosca-inclinada-halteres.webp", nome: "Rosca inclinada com halteres" },
  { arquivo: "imagens/colecao/154-triceps-polia-pegada-invertida.webp", nome: "Tríceps na polia com pegada invertida" },
  { arquivo: "imagens/colecao/155-triceps-coice-halter.webp", nome: "Tríceps coice com halter" }
];


/* -----------------------------------------------------------
   GRUPOS: quem é parecido com quem.
   O grupo sai do NOME, tanto do desenho quanto do exercício, e por
   isso funciona até para exercício criado depois pela tela. O nome é
   lido sem acento e em minúsculas, e o primeiro grupo que tiver uma
   das palavras dentro do nome é o grupo dele.

   A ORDEM IMPORTA. Panturrilha vem antes do leg press, senão a
   "Panturrilha no leg press" cairia no leg press. Supino inclinado
   vem antes de supino, reverso antes de pec deck, abdutora antes de
   glúteo ("Abdução de quadril" tem "quadril"), e assim por diante.

   Exercício cujo nome não cai em grupo nenhum fica sem o botão de
   trocar desenho: não há nada parecido para oferecer.
   ----------------------------------------------------------- */
const GRUPOS_DE_DESENHO = [
  { grupo: 'panturrilha',      palavras: ['panturrilha'] },
  { grupo: 'triceps',          palavras: ['triceps'] },
  { grupo: 'rosca',            palavras: ['rosca', 'biceps'] },
  { grupo: 'supino-inclinado', palavras: ['supino inclinado'] },
  { grupo: 'supino',           palavras: ['supino'] },
  { grupo: 'voador-inverso',   palavras: ['reverso', 'inverso', 'face pull'] },
  { grupo: 'voador',           palavras: ['pec deck', 'voador', 'crucifixo'] },
  { grupo: 'elevacao-ombro',   palavras: ['elevacao lateral', 'elevacao frontal'] },
  { grupo: 'desenvolvimento',  palavras: ['desenvolvimento'] },
  { grupo: 'puxada',           palavras: ['puxada', 'pulley', 'pullover'] },
  { grupo: 'remada',           palavras: ['remada'] },
  { grupo: 'leg-press',        palavras: ['leg press'] },
  { grupo: 'agachamento',      palavras: ['agachamento', 'hack', 'sissy', 'avanco', 'bulgaro', 'goblet'] },
  { grupo: 'extensora',        palavras: ['extensora'] },
  { grupo: 'flexora',          palavras: ['flexora'] },
  { grupo: 'abdutora',         palavras: ['abdutora', 'abducao'] },
  { grupo: 'adutora',          palavras: ['adutora', 'aducao'] },
  { grupo: 'gluteo',           palavras: ['gluteo', 'elevacao pelvica', 'quadril', 'ponte', 'pull through'] },
  { grupo: 'romeno',           palavras: ['romeno', 'rack pull', 'banco a 45'] },
  { grupo: 'abdominal',        palavras: ['abdominal', 'prancha', 'dead bug', 'exercicio de tronco'] },
  { grupo: 'barra-fixa',       palavras: ['barra fixa'] },
  { grupo: 'paralelas',        palavras: ['paralelas'] },
  { grupo: 'cardio',           palavras: ['esteira', 'bicicleta'] }
];
